### ISSUE TITLE
abort (core dumped) when doing :UpdateRemotePlugins

### ISSUE THREAD

**Issue by fantoro** [aurieh/discord.nvim#17]
Hey, I've installed this plugin with Plug but every time I run :UpdateRemotePlugins I get this
```remote/host: python3 host registered plugins []                                                                              
remote/host: generated rplugin manifest: /home/fantoro/.local/share/nvim/rplugin.vim
Press ENTER or type command to continue
```
and after that neovim aborts.

Btw I'm pretty new to plugin managers etc. in vim and this is pretty much the first time I've ever installed a plugin lol.

**Comment by aurieh** [comment]
Hello. This bug has nothing to do with the plugin, the cause is either a misconfigured system or a bug within Neovim. If you're using a source build of Neovim, you should report this issue to https://github.com/neovim/neovim. If you installed Neovim using a distribution package, you should ask in the appropriate support channels for said distribution.
