### ISSUE TITLE
WSL2: Local Discord Client Not Found.

### ISSUE THREAD

**Issue by yashguptaz** [aurieh/discord.nvim#31]
![image](https://user-images.githubusercontent.com/36479718/89000087-0da5d580-d314-11ea-8890-8ef5c6e8f793.png)
![image](https://user-images.githubusercontent.com/36479718/89000098-18606a80-d314-11ea-9b48-781ee4affe33.png)
Is there something I can do about it?

**Comment by yashguptaz** [comment]
Also I noticed that uninstalling the plugin gives a lots of errors, is there a proper procedure to uninstall this plugin?

**Comment by ObserverOfTime** [comment]
I suppose Windows doesn't map native pipes to WSL2 sockets.
So, unless Discord is also running under WSL2, it won't work.

You can try compiling and running [wine-discord-ipc-bridge](https://github.com/koukuno/wine-discord-ipc-bridge) under WSL2 and see if it works.
(Note: you should probably use `gcc` instead of `i686-w64-mingw32-gcc`.)

---

> is there a proper procedure to uninstall this plugin?

Run `:UpdateRemotePlugins` after uninstalling it.

**Comment by yashguptaz** [comment]
linux

**Comment by barsi-dev** [comment]
I'm getting the same issue.
I'm uising discord snap.

![image](https://user-images.githubusercontent.com/40544194/89573286-f78c9d80-d85c-11ea-8158-8ecfb1066cda.png)
![image](https://user-images.githubusercontent.com/40544194/89573322-02dfc900-d85d-11ea-9998-a9f9f1f0fb99.png)

**Comment by ObserverOfTime** [comment]
Don't use snap.
